<a href="https://colab.research.google.com/github/hashmatr/Pytorch/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)


2.9.0+cu126


Introduction to Tensors


Creating Tensors

In [3]:
scaler = torch.tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
Matrix = torch.tensor([[7,6],[6,3]])
Matrix

tensor([[7, 6],
        [6, 3]])

In [9]:
Matrix.ndim

2

In [10]:
Matrix.shape

torch.Size([2, 2])

In [11]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,3],
                       [4,3,2]]])

In [12]:
Tensor.ndim

3

In [13]:
Tensor.shape

torch.Size([1, 3, 3])

In [14]:
Tensor2 = torch.tensor([[[[[2,3,4],[3,4,5],[5,4,3],[1,2,3]]]]])

In [15]:
Tensor2.ndim

5

In [16]:
Tensor.shape

torch.Size([1, 3, 3])

In [17]:
Random_tensor = torch.rand(3,2)
Random_tensor

tensor([[0.0601, 0.0891],
        [0.4909, 0.8448],
        [0.4503, 0.5649]])

In [18]:
Ones = torch.ones(2,5)
Ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
zeros = torch.zeros(2,6)

Torch Range

In [20]:
Range = torch.arange(1,11)
Range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
one_to_1000 = torch.arange( start=0,end = 1000,step=77)
one_to_1000

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [22]:
tensor_zeros = torch.zeros_like(input= one_to_1000)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor datatypes**

In [23]:
float_32_tensor = torch.tensor([3.0,4.0,5.0])
float_32_tensor

tensor([3., 4., 5.])

Convert from float 32 to float 16

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [25]:
float_32_tensor*float_16_tensor

tensor([ 9., 16., 25.])

Tensors not right datatype - to do get datatype from a tenso can use 'tensor.dtype'
Tensors not right shape - to get shape from a tensor can use tensor.shape                                
Tensors not on the right device - We can use tensor.device


In [26]:
some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.6173, 0.9165, 0.6790, 0.9100],
        [0.0311, 0.6682, 0.1137, 0.1748]])

In [27]:
print(f"Data of Tensor: {some_tensor.dtype}")

Data of Tensor: torch.float32


In [28]:
## manipulating Tensors
#Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor*10

tensor([10, 20, 30])

In [30]:
tensor - 10

tensor([-9, -8, -7])

In [31]:
torch.add(tensor,10)

tensor([11, 12, 13])

Two main ways of multiplying matrix in deep learning and neural networks
1) Element wise mul.
2) Matrix Multiplication through dot product.                       
~There are two rule that performing mat mul need to satisfy otherwise we see errors
The inner dimension must match.     
'(3,2) @ (3,2)' this would not work.  
'(3,2) @ (2,3)' this would work.  
~The result has the shape of outer dimension


In [32]:
torch.matmul(tensor,tensor)

tensor(14)

In [33]:
%%time
value = 0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 721 µs, sys: 0 ns, total: 721 µs
Wall time: 787 µs


In [34]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 194 µs, sys: 29 µs, total: 223 µs
Wall time: 181 µs


tensor(14)

Main Rules of Matrix Mul

In [35]:
## one of the most important error in deep Learning : shape error

In [36]:
tensor @ tensor

tensor(14)

This example is showing the shape error in Tensor_A and Tensor_B having different number of inner dimension so take transpose of one of the tensor

In [37]:
Tensor_A = torch.tensor([[1,6,9],[2,6,9]])
Tensor_B = torch.tensor([[2,7,8],[9,7,5]])
torch.mm(Tensor_A,Tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
torch.mm(Tensor_A,Tensor_B.T)

Tensor Aggregation min,max,mean,sum etc

In [ ]:
x =  torch.arange(0,100,10)
x

In [ ]:
torch.sum(x)

In [ ]:
torch.max(x)

In [ ]:
torch.min(x)

In [ ]:
torch.mean(x.type(torch.float32))

Positional min max

In [ ]:
x.argmin()

In [ ]:
x.argmax()

## Reshaping, viewing and stacking Tensors
Reshaping : reshape an input tensor into defined shape      
View: Return the view of an input tensor of a certain shape but keeping the same mem as the original tensor.  
Stacking: Combining all tensor on top of eachother(vstack) or side by side(hstack)
Squeezing: Removing 1 D tensors from stack.  
unsqueezing: Adding 1 D tensors from stack.  
Permute: Return a view of input with dimensions permuted(swapped) in a certain way

In [ ]:
tensor = torch.arange(0,12)
tensor.shape

In [ ]:
reshaping_tensor = torch.reshape(tensor,(3,4))
reshaping_tensor.shape
reshaping_tensor

In [ ]:
#view
tensor.view(2,6)

In [ ]:
x_staked = torch.stack([tensor,tensor,tensor],dim=0)
x_staked
#

In [ ]:
tensor.unsqueeze(dim=0)

In [ ]:
tensor.squeeze()

In [ ]:
x_original = torch.rand(size=(224,224,3))
x_original.shape
x_original_permute = x_original.permute(0,2,1)
x_original_permute.shape


## Indexing in pytorch

In [ ]:
indexing = torch.arange(1,10).reshape(1,3,3)
indexing

In [ ]:
indexing[0,0,1]

In [ ]:
indexing[0][0][1]

In [ ]:
indexing[0,2,2]

In [ ]:
indexing[:,:,2]

## Numpy into tensor flow

In [ ]:
tensor1 = torch.arange(1,9)
numpy = tensor1.numpy()

In [ ]:
tensor1
numpy


In [ ]:
torch.from_numpy(numpy)


# Reproducibility

In short how neural network learns

start from random number -> tensor operations -> update random number and try to make better representation -> perfrom the operation again and again
To reduce randomness in nn and deep learig there is a concept of random seed

In [ ]:
Random_Tensor_A = torch.rand(3,4)
Random_Tensor_B = torch.rand(3,4)
print(Random_Tensor_A)
print(Random_Tensor_B)
print(Random_Tensor_A == Random_Tensor_B)

In [ ]:
torch.manual_seed(42);
Random_Tensor_A = torch.rand(3,4)
torch.manual_seed(42);
Random_Tensor_B = torch.rand(3,4)
print(Random_Tensor_A)
print(Random_Tensor_B)
print(Random_Tensor_A == Random_Tensor_B)

In [38]:
torch.cuda.device_count()

1