<a href="https://colab.research.google.com/github/hashmatr/Pytorch/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)


2.9.0+cpu


Introduction to Tensors


Creating Tensors

In [3]:
scaler = torch.tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
Matrix = torch.tensor([[7,6],[6,3]])
Matrix

tensor([[7, 6],
        [6, 3]])

In [9]:
Matrix.ndim

2

In [10]:
Matrix.shape

torch.Size([2, 2])

In [11]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,3],
                       [4,3,2]]])

In [12]:
Tensor.ndim

3

In [13]:
Tensor.shape

torch.Size([1, 3, 3])

In [14]:
Tensor2 = torch.tensor([[[[[2,3,4],[3,4,5],[5,4,3],[1,2,3]]]]])

In [15]:
Tensor2.ndim

5

In [16]:
Tensor.shape

torch.Size([1, 3, 3])

In [17]:
Random_tensor = torch.rand(3,2)
Random_tensor

tensor([[0.6021, 0.4716],
        [0.4309, 0.3476],
        [0.5491, 0.1027]])

In [20]:
Ones = torch.ones(2,5)
Ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
zeros = torch.zeros(2,6)

Torch Range

In [24]:
Range = torch.arange(1,11)
Range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
one_to_1000 = torch.arange( start=0,end = 1000,step=77)
one_to_1000

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
tensor_zeros = torch.zeros_like(input= one_to_1000)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor datatypes**

In [30]:
float_32_tensor = torch.tensor([3.0,4.0,5.0])
float_32_tensor

tensor([3., 4., 5.])

Convert from float 32 to float 16

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [33]:
float_32_tensor*float_16_tensor

tensor([ 9., 16., 25.])

Tensors not right datatype - to do get datatype from a tenso can use 'tensor.dtype'
Tensors not right shape - to get shape from a tensor can use tensor.shape                                
Tensors not on the right device - We can use tensor.device


In [34]:
some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.7076, 0.1134, 0.2381, 0.5911],
        [0.7976, 0.6572, 0.0085, 0.4317]])

In [35]:
print(f"Data of Tensor: {some_tensor.dtype}")

Data of Tensor: torch.float32


In [41]:
## manipulating Tensors
#Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor*10

tensor([10, 20, 30])

In [43]:
tensor - 10

tensor([-9, -8, -7])

In [44]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [45]:
torch.matmul(tensor,tensor)

tensor(14)

In [46]:
value = 0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
