<a href="https://colab.research.google.com/github/hashmatr/Pytorch/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)


2.9.0+cpu


Introduction to Tensors


Creating Tensors

In [35]:
scaler = torch.tensor(7)

In [36]:
scaler.ndim

0

In [37]:
scaler.item()

7

In [38]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [39]:
vector.shape

torch.Size([2])

In [40]:
Matrix = torch.tensor([[7,6],[6,3]])
Matrix

tensor([[7, 6],
        [6, 3]])

In [41]:
Matrix.ndim

2

In [42]:
Matrix.shape

torch.Size([2, 2])

In [43]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,3],
                       [4,3,2]]])

In [44]:
Tensor.ndim

3

In [45]:
Tensor.shape

torch.Size([1, 3, 3])

In [46]:
Tensor2 = torch.tensor([[[[[2,3,4],[3,4,5],[5,4,3],[1,2,3]]]]])

In [47]:
Tensor2.ndim

5

In [48]:
Tensor.shape

torch.Size([1, 3, 3])

In [49]:
Random_tensor = torch.rand(3,2)
Random_tensor

tensor([[0.0771, 0.4564],
        [0.8102, 0.8297],
        [0.2855, 0.0103]])

In [50]:
Ones = torch.ones(2,5)
Ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [51]:
zeros = torch.zeros(2,6)

Torch Range

In [52]:
Range = torch.arange(1,11)
Range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
one_to_1000 = torch.arange( start=0,end = 1000,step=77)
one_to_1000

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [54]:
tensor_zeros = torch.zeros_like(input= one_to_1000)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor datatypes**

In [55]:
float_32_tensor = torch.tensor([3.0,4.0,5.0])
float_32_tensor

tensor([3., 4., 5.])

Convert from float 32 to float 16

In [56]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [57]:
float_32_tensor*float_16_tensor

tensor([ 9., 16., 25.])

Tensors not right datatype - to do get datatype from a tenso can use 'tensor.dtype'
Tensors not right shape - to get shape from a tensor can use tensor.shape                                
Tensors not on the right device - We can use tensor.device


In [58]:
some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.0772, 0.3490, 0.1301, 0.0784],
        [0.9969, 0.8111, 0.0662, 0.6308]])

In [59]:
print(f"Data of Tensor: {some_tensor.dtype}")

Data of Tensor: torch.float32


In [60]:
## manipulating Tensors
#Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [61]:
tensor*10

tensor([10, 20, 30])

In [62]:
tensor - 10

tensor([-9, -8, -7])

In [63]:
torch.add(tensor,10)

tensor([11, 12, 13])

Two main ways of multiplying matrix in deep learning and neural networks
1) Element wise mul.
2) Matrix Multiplication through dot product.                       
~There are two rule that performing mat mul need to satisfy otherwise we see errors
The inner dimension must match.     
'(3,2) @ (3,2)' this would not work.  
'(3,2) @ (2,3)' this would work.  
~The result has the shape of outer dimension


In [64]:
torch.matmul(tensor,tensor)

tensor(14)

In [65]:
%%time
value = 0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 379 µs, sys: 1.68 ms, total: 2.06 ms
Wall time: 3.45 ms


In [66]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 108 µs, sys: 0 ns, total: 108 µs
Wall time: 113 µs


tensor(14)

Main Rules of Matrix Mul

In [ ]:
## one of the most important error in deep Learning : shape error

In [67]:
tensor @ tensor

tensor(14)

This example is showing the shape error in Tensor_A and Tensor_B having different number of inner dimension so take transpose of one of the tensor

In [71]:
Tensor_A = torch.tensor([[1,6,9],[2,6,9]])
Tensor_B = torch.tensor([[2,7,8],[9,7,5]])
torch.mm(Tensor_A,Tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [72]:
torch.mm(Tensor_A,Tensor_B.T)

tensor([[116,  96],
        [118, 105]])

Tensor Aggregation min,max,mean,sum etc

In [77]:
x =  torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
torch.sum(x)

tensor(450)

In [79]:
torch.max(x)

tensor(90)

In [80]:
torch.min(x)

tensor(0)

In [82]:
torch.mean(x.type(torch.float32))

tensor(45.)

Positional min max

In [84]:
x.argmin()

tensor(0)

In [85]:
x.argmax()

tensor(9)

## Reshaping, viewing and stacking Tensors
Reshaping : reshape an input tensor into defined shape      
View: Return the view of an input tensor of a certain shape but keeping the same mem as the original tensor.  
Stacking: Combining all tensor on top of eachother(vstack) or side by side(hstack)
Squeezing: Removing 1 D tensors from stack.  
unsqueezing: Adding 1 D tensors from stack.  
Permute: Return a view of input with dimensions permuted(swapped) in a certain way

In [88]:
tensor = torch.arange(0,12)
tensor.shape

torch.Size([12])

In [92]:
reshaping_tensor = torch.reshape(tensor,(3,4))
reshaping_tensor.shape
reshaping_tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [98]:
#view
tensor.view(2,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [100]:
x_staked = torch.stack([tensor,tensor,tensor],dim=0)
x_staked
#

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [108]:
tensor.unsqueeze(dim=0)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [105]:
tensor.squeeze()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
x_original = torch.rand(size=(224,224,3))
x_original.shape
x_original_permute = x_original.permute(0,2,1)
x_original_permute.shape


torch.Size([224, 3, 224])